### ISSUE TITLE
Missing CC Details

### ISSUE THREAD

**Issue by noshinosh** [Stanley-GF/PirateStealer#12]
![Capture11](https://user-images.githubusercontent.com/62274829/128827658-987acd65-7a42-42d1-bac2-3fd89ca9cc60.PNG)

Grabber is not able to either pull this data, or cannot read it. Is it a user end issue or an issue with the program?

**Comment by Stanley-GF** [comment]
Hmmm, I'm gonna fix it.

**Comment by Stanley-GF** [comment]
I think request body changed.

**Comment by noshinosh** [comment]
what that mean

**Comment by Quatrecentquatre-404** [comment]
> 
> 
> what that mean

If just mean the Discord API might changed for this route, which means Stanley has to update the body of the credit cards request.

**Comment by noshinosh** [comment]
is it simple to fix?

**Comment by Stanley-GF** [comment]
It is. I'll fix this night or tmrw
