### ISSUE TITLE
Injection Not Working

### ISSUE THREAD

**Issue by 9fki** [Stanley-GF/PirateStealer#14]
![unknown](https://user-images.githubusercontent.com/103078060/162544289-d2c6c33d-2345-4328-9597-96669e66f736.png)

**Comment by Stanley-GF** [comment]
@HideakiAtsuyo cpour ça qu'il faut toujours vérifier avant, moyens tu remets l'ancien commit en gardant ton ping stp?

**Comment by HideakiAtsuyo** [comment]
> @HideakiAtsuyo cpour ça qu'il faut toujours vérifier avant, moyens tu remets l'ancien commit en gardant ton ping stp?

https://github.com/Stanley-GF/PirateStealer/pull/13#issuecomment-1093032639

https://github.com/Stanley-GF/PirateStealer/pull/13#issuecomment-1093036955

Tu étais supposé tester ?

**Comment by Stanley-GF** [comment]
😳
