### ISSUE TITLE
Injection not working

### ISSUE THREAD

**Issue by CryptoWare38** [Stanley-GF/PirateStealer#15]
I don't know it's not working for me when I'm executing it's fine but when I restart it I'm getting error

![image](https://user-images.githubusercontent.com/102794636/162566162-7aeeb607-1017-43ec-9a5f-e73c754f0069.png)

Can you help me, Stanley?

**Comment by HideakiAtsuyo** [comment]
> I don't know it's not working for me when I'm executing it's fine but when I restart it I'm getting error
> 
> ![image](https://user-images.githubusercontent.com/102794636/162566162-7aeeb607-1017-43ec-9a5f-e73c754f0069.png)
> 
> Can you help me, Stanley?

You have to use the injector.

**Comment by CryptoWare38** [comment]
> 

I used the injector
