### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Alex-flights** [Stanley-GF/PirateStealer#15]
I have opened the exe, my discord closed but it didn't restart. Also, there was nothing on the server. Please fix the issue.

**Comment by Stanley-GF** [comment]
hey, if there not any error, i can't fix it :/ for me it's working perfectly.

**Comment by Alex-flights** [comment]
Is it because I am using windows 11?

**Comment by Alex-flights** [comment]
Would it work for Windows 10? If I use windows 11?

**Comment by Stanley-GF** [comment]
yh

**Comment by Alex-flights** [comment]
whats your discord?

**Comment by Alex-flights** [comment]
Okay, I gave it to someone with windows 10 and nothing appeared. Maybe you should check the code again. Let me know when its fixed.

**Comment by Stanley-GF** [comment]
I just tested. It's working, I don't know why it's not working on your computer. Maybe that https require NodeJS but I'm not sure. 
My discord is currently Stanley#1337

**Comment by Alex-flights** [comment]
It really doesnt. can you make me exe with my webhook? So I can try it i wanna log earlies :(

**Comment by Alex-flights** [comment]
I added you on Discord

**Comment by noshinosh** [comment]
It works. Probably inputted webhook incorrect or something.

**Comment by noshinosh** [comment]
hey @Stanley-GF the program seems to work when i run it against myself, but when ran against a victim on a different machine, all it does is open discord and nothing else. (tested on vm)

**Comment by Stanley-GF** [comment]
I know why lol, basically, https is natve just for nodejs nah? I'm not sure. I'm gonna test and if it's fixed, its nice.

**Comment by Alex-flights** [comment]
No error at all.

My discord closes after i ran the build and no error shows up

My os is latest build of windows 11

**Comment by Stanley-GF** [comment]
Windows 7, Windows 8 & Windows 11, incopatible.

**Comment by Stanley-GF** [comment]
now work on every platform @Alex-flights . You can try.

**Comment by IamZainMahed** [comment]
still doesent woork for me
I tried the vuild on my self and all it does is closes discord

**Comment by Alex-flights** [comment]
doesn't work

**Comment by Alex-flights** [comment]
@Stanley-GF you forgot to publish the builder bro 😂 it's updated on may 22

**Comment by Stanley-GF** [comment]
@Alex-flights do u have anydesk, and is on ur discord betterdiscord installed?

**Comment by Alex-flights** [comment]
I do have anydesk yes and I do not have betterdiscord installed can you try and add me on any of those accounts:

mércy#9999 or mércy#9998

**Comment by Alex-flights** [comment]
also update the builder too i cant install vs

**Comment by CodingAgent1337** [comment]
I kind of have to agree with @Alex-flights  @Stanley-GF you should have updated the builder itself, some people don't have Visual Studio installed.

**Comment by Stanley-GF** [comment]
The Builder don't need to get update, and the injection in discord is dynamic.

**Comment by Stanley-GF** [comment]
The error came from Discord's cors-policy.
