### ISSUE TITLE
CORS policy error

### ISSUE THREAD

**Issue by enderschesi** [Stanley-GF/PirateStealer#19]
I tried running the file and it worked fine but it doesnt send anything to the webhook. I also found this in the console 
![4pMxTMrIqe](https://user-images.githubusercontent.com/64193056/132089651-c393e6c0-8e9e-4e31-8701-829a3b97bf72.jpg)

**Comment by enderschesi** [comment]
I use Discord Canary btw

**Comment by Stanley-GF** [comment]
Aw Ok i know why, I'm gonna fix it

**Comment by Stanley-GF** [comment]
Fixed!
