### ISSUE TITLE
I've confirmed that it works, but I don't know how to get rid of it.

### ISSUE THREAD

**Issue by illegaler** [Stanley-GF/PirateStealer#2]
I run the build and tested it, and confirmed that the email address, password, and token were sent to me through the webhook.
There is nothing wrong with the tool itself, but I can't figure out how to get rid of the infected stuff.
I think it would be a good idea to add a tutorial to the readme if possible.

**Comment by Stanley-GF** [comment]
lol, ok, that easy, go in `C:\Users\[username]\AppData\Local\Discord\[appversion]\modules\discord_desktop_core-1\discord_desktop_core` and edit the index.js file for keep only `module.exports = require('./core.asar');.`

**Comment by Stanley-GF** [comment]
i'm gonna make a remover
