### ISSUE TITLE
BetterDiscord - /app:3 Uncaught DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.

### ISSUE THREAD

**Issue by LocalsGitHub** [Stanley-GF/PirateStealer#20]
getting this error in console
/app:3 Uncaught DOMException: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': The object's state must be OPENED.
    at <anonymous>:3:9

**Comment by LocalsGitHub** [comment]
im on windows 10, discord stable

**Comment by LocalsGitHub** [comment]
another error incase it helps
e92920082b09191a5bb0.js:422 Uncaught (in promise) Error: Uncaught TypeError: Cannot read property 'defaultSession' of undefined
    at Object.requireModule (e92920082b09191a5bb0.js:422)
    at e92920082b09191a5bb0.js:1192

**Comment by LocalsGitHub** [comment]
i use betterdiscord btw

**Comment by LocalsGitHub** [comment]
fixed issue by uninstalling betterdiscord, any timeline as to when betterdiscord would be supported?

**Comment by Stanley-GF** [comment]
Huh, I can selfly disable betterdiscord else I have to try to do like a bypass

**Comment by Stanley-GF** [comment]
bruh, i know why for the first errorbut for the second u sent, idk

**Comment by LocalsGitHub** [comment]
The script works fine with betterdiscord uninstalled/disabled. Do you have an idea on how to bypass the issue?

**Comment by Stanley-GF** [comment]
I'm gonna wait a pull request then accept im too lazy to fix it rn.

**Comment by HideakiAtsuyo** [comment]
> The script works fine with betterdiscord uninstalled/disabled. Do you have an idea on how to bypass the issue?

It's just a filter in the better discord script i already seen it :)

**Comment by Stanley-GF** [comment]
> The script works fine with betterdiscord uninstalled/disabled. Do you have an idea on how to bypass the issue?

You can "bypass" by doing the request using https.

**Comment by LocalsGitHub** [comment]
?
