### ISSUE TITLE
where does it duplicate itself

### ISSUE THREAD

**Issue by UnoHvH** [Stanley-GF/PirateStealer#21]
ive been testing with this and im tryna find where it duplicates itself as i wanna remove it from my rdp where does it strore it self

**Comment by Stanley-GF** [comment]
hey i didn't understand.

**Comment by NBDMatr1x** [comment]
I think he means where are the infected files in his directory

**Comment by Stanley-GF** [comment]
%localappdata%/Discord/app-[hightest number]/modules/discord-desktop-core thing/discorddesktopcore/index.js
