### ISSUE TITLE
Purpose your feature

### ISSUE THREAD

**Issue by DiscordTools69** [Stanley-GF/PirateStealer#23]
not working doset send any info in discord channel

**Comment by Stanley-GF** [comment]
Are u using BetterDiscord ?

**Comment by DiscordTools69** [comment]
yes

**Comment by Stanley-GF** [comment]
Joint discord.gg/jesusissus and send me a msg with ur anydesk id im gonna make a bp.

**Comment by Stanley-GF** [comment]
Stanley#1337

**Comment by DiscordTools69** [comment]
ok i am texting you my id is Bear

**Comment by Stanley-GF** [comment]
done.
