### ISSUE TITLE
How do i compile the grabber?

### ISSUE THREAD

**Issue by Imagine-YT** [Stanley-GF/PirateStealer#25]

**Comment by XxDarknedxX** [comment]
You gonna need to use your brain, yes skid i know this is hard for you but y'know google exists for a reason right ?

**Comment by Imagine-YT** [comment]
okay okay, STILL HELP ME

**Comment by XxDarknedxX** [comment]
> okay okay, STILL HELP ME

We can talk in discord if u want s̷ʜ̷ᴀ̷ᴅ̷ᴏ̷ᴡ̷#0001 or null#9876
