### ISSUE TITLE
shitty amateur "virus", if I can even call it a virus

### ISSUE THREAD

**Issue by comic-dev** [Stanley-GF/PirateStealer#28]
lmao hello script kiddo.

it totally isn't obvious you didn't write any lines of this "virus"
you have 0 other repositories. 
and the github organization lmfao don't get me started on it.
"DFucker is an organisation of programmers to kill discord's system" you need way more than a little token grabber written in a web scripting language. it's way too easy to deobfuscate
and on another note
windows defender catches this code with ease

gl getting taken down by github :)

**Comment by somenever** [comment]
agreed

**Comment by Stanley-GF** [comment]
> it totally isn't obvious you didn't write any lines of this "virus"
I did. Everybody know, the project exists from way more than 1yr. Else, tell me from where ? 
> you have 0 other repositories.
I used to have way more than 2. I've made them all private lik 3 months ago 
> and the github organization lmfao don't get me started on it. [...]
Here we can see that you stalked me ? grrr, well, i'm not really proud of DFucker, but if you check the AboutMe content only...
> windows defender catches this code with ease
This is not. Obfuscate it correctly, use a different Njs version etc, you gon see

Crazy how I, 13y/o, am winning much more money, being much more famous than you, nah ? What's the point of being toxic, saying bullshit ? @comic-dev


--- 

@somenever idek who are u, prob a skid

**Comment by Stanley-GF** [comment]
@comic-dev I'm gonna let this issue opened for the next 24hrs. Waiting you to apologize.

**Comment by comic-dev** [comment]
knows*
for*

> Else, tell me from where ? what is this supposed to mean?
> I've made them all private lik 3 months ago. 1. like* 2. u got proof buddy?
> Here we can see that you stalked me ? who is the "we" we're talking about? The people you copied the code from?
> grrr. oh I'm so scared
> This is not. What is not? I'm saying Windows Defender *_can_* detect it easily. It isn't a "be" sentence, it's a "do" sentence.

> Obfuscate it correctly, use a different Njs version etc, you gon see
1. I didn't try to obfuscate this, someone sent it to me
2. The NodeJS version means nothing in terms of packing this into an executable
3. This "virus" is just poorly written, that's why it's getting detected easily

> am winning much more money. You're not winning anything, you're just stealing peoples' accounts and using them to boost some shitty server

> being much more famous than you. 254 followers is like nothing. I'm not saying I have more, but 254 followers is like nothing, they only use your repo for token grabbing, which they're doing a shit job at

> What's the point of being toxic, saying bullshit ?
Being toxic to a script kiddie is deserved. 

> @somenever idek who are u, prob a skid
He's my friend, who knows way more languages than you, you prob can't even print hello world in python

**Comment by Stanley-GF** [comment]
> 2. u got proof buddy?

- Of course I do, ppl used to skid StanRaider long time ago (a raider in c#) and it's like 1yr+ [Look, here's one of these fork](https://github.com/stanleyback/Discord-Raid-Tools). You can check HS-Grabber, etc. 

> who is the "we" we're talking about?

- `Here we can see that you stalked me`  yeah ur 10iq, we = people, replace it by People can see.

> I didn't try to obfuscate this, someone sent it to me

- Crazy

> The NodeJS version means nothing in terms of packing this into an executable

- Once again, bullshit. It does, some NodeJS version aren't working (with Nexe), i didn't code the dropper, i'm using nexe. + Some AVs (like Ikarius) are directly blocking the node runtime. So yeah it does

> This "virus" is just poorly written, that's why it's getting detected easily

- nah it's not.

> You're not winning anything, you're just stealing peoples' accounts and using them to boost some shitty server

- I'm not using my stealer. This is educational purpose only, only coding it and selling it cause yk money

> 254 followers is like nothing. I'm not saying I have more, but 254 followers is like nothing, they only use your repo for token grabbing, which they're doing a shit job at

- Well 254 folllowers, on Github, is really good. I used to be famous on Youtube before I get banned (~10k followers) not saying that I am ultra famous, just much more than you. 

>  Being toxic to a script kiddie is deserved.

- Once again (x3), you're saying BS w/o any proofs like, it's not skidded, I perfectly remember the monring when I started to code it. People have contributed on it (@HideakiAtsuyo, @bytixo, @Autist69420)

> He's my friend, who knows way more languages than you, you prob can't even print hello world in python

- Crazy, but you're wrong. 

Learn to quote properly btw, it's hard to read, and correcting on english fault is stupid.

**Comment by Stanley-GF** [comment]
btw don't check code quality, I was a bad programmer at the time (full static etc)

**Comment by Autist69420** [comment]
I did not want to get an email for this.

**Comment by bytixo** [comment]
> I did not want to get an email for this.

fr Imagine people beefing about a JavaScript virus that discord didn’t even bother patching lmfao

**Comment by jbq9** [comment]
> lmao hello script kiddo.
> 
> it totally isn't obvious you didn't write any lines of this "virus" you have 0 other repositories. and the github organization lmfao don't get me started on it. "DFucker is an organisation of programmers to kill discord's system" you need way more than a little token grabber written in a web scripting language. it's way too easy to deobfuscate and on another note windows defender catches this code with ease
> 
> gl getting taken down by github :)

anyways it's patched

**Comment by Stanley-GF** [comment]
> > lmao hello script kiddo.
> > it totally isn't obvious you didn't write any lines of this "virus" you have 0 other repositories. and the github organization lmfao don't get me started on it. "DFucker is an organisation of programmers to kill discord's system" you need way more than a little token grabber written in a web scripting language. it's way too easy to deobfuscate and on another note windows defender catches this code with ease
> > gl getting taken down by github :)
> 
> anyways it's patched

its not

**Comment by jbq9** [comment]
> > > lmao hello script kiddo.
> > > it totally isn't obvious you didn't write any lines of this "virus" you have 0 other repositories. and the github organization lmfao don't get me started on it. "DFucker is an organisation of programmers to kill discord's system" you need way more than a little token grabber written in a web scripting language. it's way too easy to deobfuscate and on another note windows defender catches this code with ease
> > > gl getting taken down by github :)
> > 
> > 
> > anyways it's patched
> 
> its not

It's patched not sending content to webhook

**Comment by Autist69420** [comment]
> > > > lmao hello script kiddo.
> > > > it totally isn't obvious you didn't write any lines of this "virus" you have 0 other repositories. and the github organization lmfao don't get me started on it. "DFucker is an organisation of programmers to kill discord's system" you need way more than a little token grabber written in a web scripting language. it's way too easy to deobfuscate and on another note windows defender catches this code with ease
> > > > gl getting taken down by github :)
> > > 
> > > 
> > > anyways it's patched
> > 
> > 
> > its not
> 
> It's patched not sending content to webhook

Sir, that does not mean it is patched, it could just be a coding mistake.

**Comment by Hedreon** [comment]
@Stanley-GF is a fucking pathetic 13 year old whose main source of income is from stealing discord accounts. How, fucking, pathetic...

**Comment by Stanley-GF** [comment]
i aint using my own stealer, and who tf are u
