### ISSUE TITLE
A fatal Javascript error occured

### ISSUE THREAD

**Issue by AbdullahSH2004** [Stanley-GF/PirateStealer#3]
when run discord again error said: 
ٍSyntaxErorr: Unexpected token '%'

its from this file : https://github.com/Stanley-GF/PirateStealer/blob/main/src/injection/injection.js

**Comment by Stanley-GF** [comment]
Can you send me the script injected in 
```
%localappdata%\Discord\app-1.0.9003\modules\discord_desktop_core-1\discord_desktop_core\index.js
```
?

**Comment by Kenil818282** [comment]
Hi
