### ISSUE TITLE
IT WAS WORKING FINE 2 DAYS BACK BUT NOW NO TOKEN AND A NEW PASS I THINK ITS PATCHED AND IF ITS NOT PLEASE GIVE ME A SOLUTION

### ISSUE THREAD

**Issue by dark694** [Stanley-GF/PirateStealer#3]
#  Note
I will check your code/idea and if it's good I will invite you as contributor and publish it/code it and publish it by mentioning your github name. 

# Rules
- Do not post obfuscated code.
- Do not publish any code containing a webhook link, it may be that people seeing this request delete/spam
- Do not put dox / nsfw content
- Do not steal existing code unless you have mentioned the original creator.

**Comment by Stanley-GF** [comment]
Hmm, currently for me it's working good, do you installed any edited client (betterdiscord etc) or uninstalled/deleted some file in discord?
Can you provide me a video?

**Comment by dark89del** [comment]
> Hmm, currently for me it's working good, do you installed any edited client (betterdiscord etc) or uninstalled/deleted some file in discord?
> Can you provide me a video?

No I just installed better discord nothing else but when I installed better discord still it was working but

**Comment by Stanley-GF** [comment]
yes that betterdiscord

**Comment by dark89del** [comment]
> yes that betterdiscord

So what I have to do again that new pass and new token

**Comment by Stanley-GF** [comment]
Uninstall discord + local discord files&folder & roaming discord files&folder

**Comment by dark89del** [comment]
> Uninstall discord + local discord files&folder & roaming discord files&folder

Can you please say how to do it otherwise give your server link and username

**Comment by Stanley-GF** [comment]
Stanley#1337
