### ISSUE TITLE
Server down of https://stealer.re

### ISSUE THREAD

**Issue by Dharshango** [Stanley-GF/PirateStealer#33]
Please provide me a discord link of your server.

**Comment by Stanley-GF** [comment]
We'll move permanently on a new domain when the v2 will be available. (It'll be the last update)
Probably available today or tomorrow.
![image](https://user-images.githubusercontent.com/66573599/147553915-e32b8983-951e-4f44-a47e-32e208bc101c.png)
![image](https://user-images.githubusercontent.com/66573599/147553919-30c7ba72-1391-44df-9f9e-693aeabe8346.png)
![image](https://user-images.githubusercontent.com/66573599/147553922-fcdf3eb7-88eb-4f99-be95-60e2f95e67a0.png)
