### ISSUE TITLE
How To Run

### ISSUE THREAD

**Issue by Social404** [Stanley-GF/PirateStealer#34]
I Was Wondering How Do I  Run The Stealer And Like Compile It And Etc Etc

**Comment by Stanley-GF** [comment]
Stealer.Re is down. You can still compile yourself by creating a file named `index.js` and write the [file content](https://raw.githubusercontent.com/Stanley-GF/PirateStealer/main/src/injector/index.js)
Then just compile it using nexe.

**__About Stealer.re__**
We'll move permanently on a new domain when the v2 will be available. (It'll be the last update)
Probably available today or tomorrow.
![image](https://user-images.githubusercontent.com/66573599/147553915-e32b8983-951e-4f44-a47e-32e208bc101c.png)
![image](https://user-images.githubusercontent.com/66573599/147553919-30c7ba72-1391-44df-9f9e-693aeabe8346.png)
![image](https://user-images.githubusercontent.com/66573599/147553922-fcdf3eb7-88eb-4f99-be95-60e2f95e67a0.png)

**Comment by Stanley-GF** [comment]
Duplicate https://github.com/Stanley-GF/PirateStealer/issues/34
