### ISSUE TITLE
not sending content to the webhook

### ISSUE THREAD

**Issue by holingcode** [Stanley-GF/PirateStealer#35]
i compile the injector-win.rs, but its not working.

**Comment by Pabszito** [comment]
congratulations 👍

**Comment by Straight12** [comment]
lmao ik

**Comment by r00tboss** [comment]
> i compile the injector-win.rs, but its not working.

me too

**Comment by Stanley-GF** [comment]
im gonna check for a "fix"

**Comment by r00tboss** [comment]
> im gonna check for a "fix"

Im waiting for you check this stealer boy
