### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Devilontop23** [Stanley-GF/PirateStealer#39]
when i m trying to build free pirate stealer it says cannot build/86 this

**Comment by Stanley-GF** [comment]
Screenshot ?

**Comment by Devilontop23** [comment]
`
![Screenshot_20220107-094550_Firefox](https://user-images.githubusercontent.com/97110679/148490749-f1f5b501-6cb2-4180-ba35-2e0ec378e7da.jpg)
`

When I insert webhook url and icon in it then click on build it shows always this

**Comment by Devilontop23** [comment]
![Uploading Screenshot_20220107-094550_Firefox.jpg…]()

**Comment by Devilontop23** [comment]
Please check the screenshot

**Comment by Stanley-GF** [comment]
Use another browser (chrome, all chrominium based, opera, brave etc)

**Comment by Devilontop23** [comment]
Can u check ur Twitter once I have dmed u to buy pirate stealer premium
