### ISSUE TITLE
What is "core.asar" ?

### ISSUE THREAD

**Issue by xvzontop** [Stanley-GF/PirateStealer#4]
i see module.export(./core.asar) whats that?

**Comment by Stanley-GF** [comment]
Why u want to know?

**Comment by Autist69420** [comment]
basically the main file that does the magic stuff to make it work,
![image](https://user-images.githubusercontent.com/56086819/160101795-dd03a29c-be6b-4af5-9ac2-f4a1202869e0.png)

**Comment by PndaBoi** [comment]
:O

**Comment by DoCt0rAnTiPlAgUe** [comment]
Yeah, But how i can get the core.asar file?
