### ISSUE TITLE
Pirate Stealer "remover"

### ISSUE THREAD

**Issue by theanshshow** [Stanley-GF/PirateStealer#46]
i cant remember which one was the token logger. but its one of them. it was a discord account raper. i would say use a vm and a test discord account to test which one. sorry for forgetting :/
![image](https://user-images.githubusercontent.com/92476451/150660601-9a39badb-5b39-4b70-98c7-ea31c37ffdf5.png)

**Comment by Stanley-GF** [comment]
Lemme check that. Ty !

**Comment by theanshshow** [comment]
np
