### ISSUE TITLE
No address returned when adding CC

### ISSUE THREAD

**Issue by VerstreuteSeele** [Stanley-GF/PirateStealer#47]
Hey. Seems to be like discord changes something. When adding a CC the webhook already fires after adding the CVC & card holders name and does not wait till the "next" button is clicked and the other fields are filled out resulting in all the address fields returning "undefined". any quick fix for that I can throw into the inject-clean code?

also, since discord asks for "name on card" couldn't that be returned as well?

**Comment by VerstreuteSeele** [comment]
also, since discord asks for "name on card" couldn't that be returned as well?

**Comment by Stanley-GF** [comment]
Actually I can't (im too lazy) to fix that shit, it's cause now, Stripe need 2 requests, one for card confirmation and the second one for billing address confirmation. Actually, you can put the info u want the billing info, cause they do not verify
