### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Sh4rK157** [Stanley-GF/PirateStealer#7]
It was working just fine for 2 days, but now it suddenly stopped working, I tried reinstalling discord and even resetting my computer but I think it's patched.

**Comment by Stanley-GF** [comment]
Send me a ss of the error

**Comment by bytixo** [comment]
Atleast provide some info on what is not working ... Does it fail to edit the index.js, does it fails to put your webhook in it etc ...

**Comment by Stanley-GF** [comment]
Hm

**Comment by jojo160819888** [comment]
moi quand jai fini de bien le build est que je le lance pour esseyer sa nenvoie rien

**Comment by Stanley-GF** [comment]
Étrange. Je sais pourquoi et jvends le code update et tout car j'suis cool 😎 donc stv le full fix avec des options en + et toute les erreurs en moins etc viens MP sur discord sinon bah essaye sur quelqu'un d'autre

**Comment by Stanley-GF** [comment]
Close for inactivity
