### ISSUE TITLE
PIRATE STEALER IS DUALHOOKED AND OWNER IS TRYING TO COVER IT UP

### ISSUE THREAD

**Issue by DiscordBotTester** [Stanley-GF/PirateStealer#7]
# Thanks to qoft for this copypasta

Pirate stealer (https://github.com/Stanley-GF/PirateStealer) is DUAL HOOKED

If you have ran pirate stealer, got to C:\Users\YOUR PC NAME\AppData\Local\Discord\app-1.0.9003\modules\discord_desktop_core-1\discord_desktop_core and replace the everything in index.js with module.exports = require('./core.asar');,

dual hooked as in they get the tokens too
not just you
story:

my friends were messing around with pirate stealer, we were seeing it if it actually worked and then yeah, one of the admins & stanly himself had access to the account bc they were talking on it. then account went offline, (probable changed pass so stanly can give the account back) and then the person on the account started being nice and gave the account back, as in before the person on the account was being like "fuck you skid" and shit like that

https://cdn.discordapp.com/attachments/919250472689360896/919356383260975184/2021-12-11_17-25-18.mp4 proof to support evidence

**Comment by Stanley-GF** [comment]
If you wouldn't have a superhuman brain, you would have noticed that the only thing he does is tell a story. Without any proof
