### ISSUE TITLE
pirateskid more like stanly likes men

### ISSUE THREAD

**Issue by Kxifed** [Stanley-GF/PirateStealer#8]
![5xjlox](https://user-images.githubusercontent.com/68350865/145696111-2db9c662-440b-4c17-aeeb-4dd5d2111cf2.jpg)

**Comment by Stanley-GF** [comment]
tf

**Comment by Kxifed** [comment]
![5xjlox.jpg](https://user-images.githubusercontent.com/68350865/145711855-5f9fc3db-1dea-4633-829e-ca11094de169.jpg)
