### ISSUE TITLE
Its Not working Now

### ISSUE THREAD

**Issue by JoshK47YT** [Stanley-GF/PirateStealer#8]
It was Working but after a Few Days it Stopped Working i did everthing and still not working

**Comment by Stanley-GF** [comment]
Ok send me a ss of the error. I'll fix it

**Comment by JoshK47YT** [comment]
> Ok send me a ss of the error. I'll fix it
Well It Worked After a Day I am sorry To Bother You Thanks For Replying I hope You make More Things

**Comment by JoshK47YT** [comment]
> Ok send me a ss of the error. I'll fix it

Well It Worked After a Day I am sorry To Bother You Thanks For Replying I hope You make More Things
