### ISSUE TITLE
Obfuscator

### ISSUE THREAD

**Issue by akaBrook** [Stanley-GF/PirateStealer#9]
Can post working obfuscator for this grabber?

**Comment by Stanley-GF** [comment]
What do you mean? JS or .NET obfuscator?

**Comment by Stanley-GF** [comment]
closed for inactivity

**Comment by Stanley-GF** [comment]
i'll publish an API for autoobfuscating soon.

**Comment by apolo1337** [comment]
can publish the api for obfuscate, people is destroying my webhook

**Comment by NBDMatr1x** [comment]
lmao U getting webhook nuked. Thats a rip
